### ISSUE TITLE
Headless mode for testing

### ISSUE THREAD

**Issue by neuromancer** [dpjudas/SurrealEngine#10]
It will be nice to allow UTEngine to have a headless mode that just parses media files and scripts from a Unreal/UT installation. This will allow to run different versions of demos in the CI to ensure everything works as expected.

**Comment by dpjudas** [comment]
I agree that I should really improve the startup part of the project. Especially now that others seem to be trying it out. Adding a headless mode for that shouldn't be much of a problem.

I'm not sure if we can run the demo versions in the CI that easily. They are copyrighted so we at least need to make sure we can host those legally.

**Comment by dpjudas** [comment]
Yes that would probably work. I'm not sure what archive.org thinks about us constantly downloading from them though. Maybe we could create a repository for the files that CI then grabs or something along those lines.
