### ISSUE TITLE
OpenGL Render or Software Render

### ISSUE THREAD

**Issue by demensdeum** [dpjudas/SurrealEngine#112]
Got SurrealEngine compiled on Emscripten, but at the end stuck with error:
`Unable to create SDL Window: Vulkan support is either not configured in SDL or not available in current SDL video driver (emscripten) or platform`
that's because Emscripten doesn't support Vulkan still.
I can try to write OpenGL renderer for SurrealEngine, or there is any easy option, for example Software Renderer builtin?
Fork url:
https://github.com/demensdeum/SurrealEngine-Emscripten

**Comment by dpjudas** [comment]
This currently only a vulkan render device. There is no software renderer.

Fancy with an emscripten port! Unfortunately you'd also need the game files and those would be problematic to include if you're attempting to run it in a web browser. :)

**Comment by demensdeum** [comment]
It's actually working with cmake flags:
--preload-file UnrealTournament/ --preload-file SurrealEngine.pk3
I see that game starts, resources got loaded, but at end I got this error about Vulkan renderer.
Thank you, I will try to implement OGLES renderer then.

**Comment by LupertEverett** [comment]
> Unfortunately you'd also need the game files and those would be problematic to include if you're attempting to run it in a web browser. :)

They can use the demo files I think, iirc the UT emscripten port was doing exactly that.

Also kinda late to the convo here, but if you're gonna write an OpenGL renderer, feel free to take my unfinished code as the base.

**Comment by demensdeum** [comment]
@LupertEverett yes I think to use UT99 demo files. Thank you for suggestion about your OpenGL renderer code, I will check

**Comment by aktau** [comment]
I know this is late to the party, but I saw https://demensdeum.com/blog/2024/07/16/surreal-engine-cpp-webassembly-port/ and started thinking about a port to the PS Vita. It's from the same era as Quake III (https://github.com/Rinnegatamante/vitaQuake) so it should run fine (there are far more visually impressive games on the Vita). An earlier version of the Unreal engine also already runs (https://github.com/fgsfdsfgs/UE1). I don't know about the legal status of the latter, and havnen't looked at the code, but it's clear it works.

Two questions to @dpjudas and other maintainers:

 1. Would a `GLES2RenderDevice` be accepted upstream?
 2. Would modifications to allow building for PS Vita (arm32, VitaSDK) be accepted upstream?

It's not that big of a problem to maintain a fork, especially for #2, but for point 1 it'd be useful to maintain a simplistic  backend upstream and verify with CI that it at least builds.

**Comment by dpjudas** [comment]
Yes, support for other render devices would be accepted. Same for build system modifications for targeting other systems.

But as always with software, the devil is in the detail. It really comes down how its done. If it splits things cleanly with proper platform abstractions its all very welcome. If its a mess of #ifdefs all over the codebase then we'd probably request changes before accepting. 

We have a channel on discord if you want to discuss specifics - or you can file pull requests and we can take it from there. :)

**Comment by aktau** [comment]
It's good to know that new render backends and platforms are OK in principle.

I agree about the maintainability of it all. If I put myself in your shoes, I'd want the same. I'm sure there will be `ifdef`'s, but they should be fairly limited all things considered (Vita has a libc-alike, OpenGL-style headers, an OpenAL implementation, et cetera).

I don't want to cookie lick though, I don't have a lot of unallocated free time, and a lot of things are unfamiliar territory for me (I don't even have a proper Vita dev setup at the moment, which will be the second step after getting SurrealEngine to build for linux/arm32). **If** I get time for it, I'll likely open a PR to iterate on.
