### ISSUE TITLE
Fatal error: immintrin.h: No such file or directory

### ISSUE THREAD

**Issue by leilei-** [dpjudas/SurrealEngine#12]
armhf raspbian

(this is the eventual obligatory pi compilation thread)

**Comment by dpjudas** [comment]
Okay I fixed this, but honestly there's so many other issues right now that I doubt anyone would actually run it on a pi. :)

**Comment by leilei-** [comment]
Thanks! It compiles up to a error about dumb now. GCC 8.3.0 may be fussy about dumb.

In file included from /utengine/UTEngine/Audio/AudioSource.cpp:28: /utengine/Thirdparty/dumb/include/dumb.h:143:47: error: negative width in bit-field 'dumb_off_t_needs_to_be_at_least_8_bytes::dumb_off_t_needs_to_be_at_least_8_bytes_'
         : ((sizeof(dumb_off_t) >= 8) ? 1 : -42);

running UT in box86 on a Pi4's a mess of broken sound and completely wrong speed fyi, so i thought i'd try this on it (out of curiosity).

**Comment by dpjudas** [comment]
Dumb not compiling is a bit of a problem as that is the library used to play the tracker music. UTEngine is just consuming that library, so your guess is as good as mine for why it doesn't compile.

It is quite possible dumb was never ported to ARM, or maybe it is expecting some defines to be set? If so, CMakeLists.txt needs special checks for ARM that then sets those defines.

**Comment by leilei-** [comment]
the only shoulder-shrugging input i have on that matter is that OA uses libxmp for playing mods and that works on pi, but also i've heard it have issues with UT's mods and don't know if they've fixed that in the years since because I haven't tried them lately.

**Comment by dpjudas** [comment]
dumb doesn't seem to be playing all the songs either. I guess one could always search for a better music playback library some day. :)
