### ISSUE TITLE
Add apt command to install dev packages required to README.md

### ISSUE THREAD

**Issue by gmt4** [dpjudas/SurrealEngine#128]
Adding something like the apt command below to the README , under a "Ubuntu build" subsection could be handy:

~~~
apt install cmake g++ libasound-dev libopenal-dev libdbus-1-dev libsdl2-dev libxkbcommon-dev libwayland-dev
~~~

The above worked for me on Ubuntu, might work for others too.

(Edited to add missing: `libopenal-dev`)

**Comment by LupertEverett** [comment]
Surprised libwayland-dev worked there, as we use waylandpp (C++ bindings for Wayland) instead of the C bindings.

Other than that, it is a pretty good idea imo!

**Comment by gmt4** [comment]
I did a X11/sdl2 build, so  maybe `libwayland-dev` is unused, but includes the x11-dev packages required to build on x11.

**Comment by LupertEverett** [comment]
> I did a X11/sdl2 build, so maybe `libwayland-dev` is unused, but includes the x11-dev packages required to build on x11.

That's probably the case. No Wayland builds are done at all if waylandpp isn't found (the check is performed in ZWidget's CMakeLists.txt).

**Comment by gmt4** [comment]
Right, I removed `libwayland-dev` and, added `waylandpp-dev`, which pulls all the `libwayland-client++` deps, and got a wayland build. 

~~~
apt install cmake g++ libasound-dev libopenal-dev libdbus-1-dev libsdl2-dev libxkbcommon-dev waylandpp-dev
~~~

**Comment by LupertEverett** [comment]
Made a PR is regarding this!

**Comment by LupertEverett** [comment]
And it got merged, so I think this issue can be closed now
