### ISSUE TITLE
Request for feedback on NixOS package

### ISSUE THREAD

**Issue by hughobrien** [dpjudas/SurrealEngine#129]
Hey guys, thank you so much for this work.

I'd like to port this to Nix/NixOS, and have an open PR https://github.com/NixOS/nixpkgs/pull/337069

Would appreciate any feedback!

Please feel free to close this issue.

**Comment by LupertEverett** [comment]
I checked out the PR you've linked, and noticed this particular line:

> Note the binary requires SurrealEngine.pk3 to be available on the path. I tried adding to $out/lib but no dice. Open to suggestions/wrappers to keep it out of bin

We can add additional folders to check for Linux. How does `/usr/share/surrealengine` sound?

**Comment by hughobrien** [comment]
Perfect, I can patch that as part of the build which is pretty standard on NixOS. PR updated.

**Comment by LupertEverett** [comment]
Just noticed the PR got closed. Did something happen?

**Comment by hughobrien** [comment]
It got stale, I'll re-open it
