### ISSUE TITLE
UT99 - Input Settings Not Saved

### ISSUE THREAD

**Issue by hughobrien** [dpjudas/SurrealEngine#144]
Changing the controller input keys to standard WASD seems to work, but when you close the config dialog and open it again they have reset.

I don't see any 'save' option so unless I'm missing that I think it might be a bug.

Latest build.

**Comment by LupertEverett** [comment]
Yeaaaahhhh it is not properly implemented yet. I tried to dabble with it myself once upon a time, but it seems that the code I wrote doesn't work.

**Comment by hughobrien** [comment]
Here's a simple direct patch to the config file for anyone else. NB: Inverts Y.

```patch
diff --git a/drive_c/UnrealTournament/System/SE-User.ini b/drive_c/UnrealTournament/System/SE-User.ini
index 4297cef..41c7cad 100644
--- a/drive_c/UnrealTournament/System/SE-User.ini
+++ b/drive_c/UnrealTournament/System/SE-User.ini
@@ -81,7 +81,7 @@ G=Grab
 L=Taunt wave
 M=Look
 O=Toggle bExtra0
-S=Axis aUp Speed=+300.0
+S=MoveBackward
 T=Talk
 Z=Strafe
 F1=ShowScores
@@ -117,9 +117,9 @@ Print=
 Execute=
 PrintScrn=
 Help=
-A=
+A=StrafeLeft
 B=
-D=
+D=StrafeRight
 E=
 f=Feigndeath
 H=Taunt Thrust
@@ -131,7 +131,7 @@ Q=GetWeapon BotPack.Translocator
 R=TeamTalk
 U=
 V=
-W=
+W=MoveForward
 X=
 NumPad0=ViewPlayerNum 0
 NumPad1=ViewPlayerNum 1
@@ -228,6 +228,7 @@ WeaponPriority=None
 WeaponPriority=None
 WeaponPriority=None
 WeaponPriority=None
+bInvertMouse=True
 
 [Engine.HUD]
 HudMode=0
```

**Comment by LupertEverett** [comment]
After a bit of going through the hell that is UMenu classes, I've discovered (in UMenuCustomizeClientWindow) that the keys are set with `set input ...` console command, which I don't think we handle them yet.
