### ISSUE TITLE
`Segmentation fault when running` on Linux

### ISSUE THREAD

**Issue by Clovergruff** [dpjudas/SurrealEngine#24]
I can't seem to be able to launch UTEngine under Linux, it throws:
```
Segmentation fault (core dumped)
```
I'm running EndeavourOS with KDE
CPU - AMD Ryzen 7 3700X (16) @ 3.600G
GPU - AMD ATI Radeon RX 5600 OEM/5600
RAM - 32Gb

I previously had the same issue on Manjaro as well, perhaps UTEngine has issues on Arch based distros?

**Comment by dpjudas** [comment]
I haven't launched UTEngine on Linux for a while - it could be something related to your choice of distro - or it could be crashing for everyone. The Linux support is pretty low priority currently. I will fix it at some point though.

**Comment by OrdinaryMagician** [comment]
Seems the crash happens in a call to Engine::LogMessage while loading the Engine.Actor class, over some sort of "unknown property".

My UT install is patched to 469 so it might be just that, though. I'll reinstall 436 and see if it still happens.

**Comment by dpjudas** [comment]
UTEngine is made to work with 436. We can't really support 469 as it is such a moving target. They are doing all kinds of changes to the engine that would take too much time to track down.

It doesn't surprise me that it crashes on something like vkGetPhysicalDeviceXlibPresentationSupportKHR. That means it is crashing for all Linux boxes currently.

**Comment by dpjudas** [comment]
I fixed the null pointer crash. It now works on my Linux box, at least.

**Comment by OrdinaryMagician** [comment]
Got it to run now, although it crashed my nvidia drivers.
