### ISSUE TITLE
Linux (Arch) compile errors

### ISSUE THREAD

**Issue by JPLeBreton** [dpjudas/SurrealEngine#33]
```
In file included from SurrealEngine/Thirdparty/ZVulkan/src/vk_mem_alloc/vk_mem_alloc.cpp:8:
SurrealEngine/Thirdparty/ZVulkan/include/zvulkan/vk_mem_alloc/vk_mem_alloc.h: In function ‘void VmaUint32ToStr(char*, size_t, uint32_t)’:
SurrealEngine/Thirdparty/ZVulkan/include/zvulkan/vk_mem_alloc/vk_mem_alloc.h:2410:9: error: ‘snprintf’ was not declared in this scope
```

and

```
SurrealEngine/Thirdparty/ZVulkan/src/vulkanswapchain.cpp: In member function ‘void VulkanSwapChain::Create(int, int, int, bool, bool, bool)’:
SurrealEngine/Thirdparty/ZVulkan/src/vulkanswapchain.cpp:51:36: error: ‘runtime_error’ is not a member of ‘std’
```

Pretty sure I have all the dependencies installed, I was able to compile the project successfully on this same setup earlier this year.

**Comment by dpjudas** [comment]
Probably just a question of missing includes that for some reason only materialize themselves on Arch? The build tests are passing on GitHub.

Try add "#include <stdexcept>" to the top of SurrealEngine/Thirdparty/ZVulkan/src/vulkanswapchain.cpp
And try add "#include <cstdio>" to the top of SurrealEngine/Thirdparty/ZVulkan/include/zvulkan/vk_mem_alloc/vk_mem_alloc.h

Does that fix the problem?

**Comment by JPLeBreton** [comment]
> Try add "#include " to the top of SurrealEngine/Thirdparty/ZVulkan/src/vulkanswapchain.cpp And try add "#include " to the top of SurrealEngine/Thirdparty/ZVulkan/include/zvulkan/vk_mem_alloc/vk_mem_alloc.h

`error: #include expects "FILENAME" or <FILENAME>`

was there a particular filename that was supposed to be in those includes?

**Comment by dpjudas** [comment]
Ah it seems that html ate the &lt; and &gt; tags. It was supposed to say #include &lt;stdexcept&gt; and #include &lt;cstdio&gt;

**Comment by JPLeBreton** [comment]
> Ah it seems that html ate the < and > tags. It was supposed to say #include <stdexcept> and #include <cstdio>

Ah, makes sense. I included stdexcept to the top of vulkanswapchain.cpp and both stdexcept and cstdio to vk_mem_alloc.h, and the project compiled.

When I run ./SurrealEngine [my UT directory], it doesn't launch and prints "stoi" to stdout. In case it's relevant, the only compile warnings I get are a few like this one:
```
[ 14%] Building C object CMakeFiles/SurrealCommon.dir/Thirdparty/dumb/src/helpers/resample.c.o
In file included from SurrealEngine/Thirdparty/dumb/src/helpers/resamp2.inc:106,
                 from SurrealEngine/Thirdparty/dumb/src/helpers/resample.inc:165,
                 from SurrealEngine/Thirdparty/dumb/src/helpers/resample.c:149:
SurrealEngine/Thirdparty/dumb/src/helpers/resamp3.inc: In function ‘dumb_resample_1_1’:
SurrealEngine/Thirdparty/dumb/src/helpers/resamp3.inc:60:26: warning: integer overflow in expression ‘-2147483648’ of type ‘int’ results in ‘-2147483648’ [-Woverflow]
   60 |     if (dt == 0 || dt == -(int)0x80000000)
      |                          ^
```

**Comment by dpjudas** [comment]
I'm afraid I have no idea why it would write "stoi" to stdout. Perhaps it encountered a string that couldn't be converted to an integer? Note that UT has to be version 436 - any 469 version will not function.

It worked on Linux Mint the last time I tested it.

**Comment by JPLeBreton** [comment]
I'll have a look on my end then, the compile issues originally reported are fixed. Thanks!

**Comment by mcneb10** [comment]
Can confirm this happens on my arch linux machine

**Comment by JPLeBreton** [comment]
Here are the only code changes needed as of this moment to get the current main branch compiling on my system:

```
diff --git a/Thirdparty/ZVulkan/src/vulkanbuilders.cpp b/Thirdparty/ZVulkan/src/vulkanbuilders.cpp
index 652cd63..f5e43f2 100644
--- a/Thirdparty/ZVulkan/src/vulkanbuilders.cpp
+++ b/Thirdparty/ZVulkan/src/vulkanbuilders.cpp
@@ -1,4 +1,4 @@
-
+#include <stdexcept>
 #include "vulkanbuilders.h"
 #include "vulkansurface.h"
 #include "vulkancompatibledevice.h"
diff --git a/Thirdparty/ZVulkan/src/vulkanswapchain.cpp b/Thirdparty/ZVulkan/src/vulkanswapchain.cpp
index 9162109..ba528a9 100644
--- a/Thirdparty/ZVulkan/src/vulkanswapchain.cpp
+++ b/Thirdparty/ZVulkan/src/vulkanswapchain.cpp
@@ -1,4 +1,4 @@
-
+#include <stdexcept>
 #include "vulkanswapchain.h"
 #include "vulkanobjects.h"
 #include "vulkansurface.h"
```

ie adding "#include \<stdexcept\>" to vulkanbuilders.cpp and vulkanswapchain.cpp.

I can't confirm those changes don't break compiling on any other system, but if not then patching that is pure upside. Thanks for the help troubleshooting.

**Comment by JPLeBreton** [comment]
Regarding the "stoi" log on failure to launch, I must have had something different about my System/ subdir that the engine didn't like; when I used a version of System/ fresh from the GOTY Edition CD the game loaded up fine.
