### ISSUE TITLE
editor segfaults on Linux

### ISSUE THREAD

**Issue by Mis012** [dpjudas/SurrealEngine#52]
Trying to launch the editor seems to result in the following segfault (launching the game works fine)
Not sure if this is also the case on windows, and getting the editor to launch is still WIP? The README seems to have outdated information about the status of the project, since ut99 looks much closer to playable than it would let on.

```
>gdb --args ./SurrealEditor ~/sata_ssd/Games/ut99_surrealengine/
...
Thread 1 "SurrealEditor" received signal SIGSEGV, Segmentation fault.
0x00005555556a6194 in UActor::UpdateBspInfo (this=0x55555a38fd40)
    at SurrealEngine/SurrealEngine/UObject/UActor.cpp:1731
1731			BspNode* node = &level->Model->Nodes[0];
(gdb) p level
$1 = (ULevel *) 0x0
```

the following patch was used to work around a hardcoded windows path (and the exact font was installed, just in case)
```diff
diff --git a/SurrealEngine/UI/Core/Canvas.cpp b/SurrealEngine/UI/Core/Canvas.cpp
index eb93805..b837be8 100644
--- a/SurrealEngine/UI/Core/Canvas.cpp
+++ b/SurrealEngine/UI/Core/Canvas.cpp
@@ -36,7 +36,12 @@ class CanvasFont
 public:
 	CanvasFont(const std::string& fontname, double height) : fontname(fontname), height(height)
 	{
+// TODO: don't hardcode this
+#ifdef WIN32
 		data = File::read_all_bytes("C:\\Windows\\Fonts\\segoeui.ttf");
+#else
+		data = File::read_all_bytes("/usr/share/fonts/truetype/segoeui.ttf");
+#endif
 		loadFont(data.data(), data.size());
 
 		try
```

**Comment by Mis012** [comment]
well, yes, it's not *playable*, but it's for sure further along than the README implies
I gather that the editor is not supposed to dereference NULL pointers though?

**Comment by Mis012** [comment]
launches fine now :+1: 

![image](https://github.com/dpjudas/SurrealEngine/assets/10321751/bb65d254-98cc-49a3-b138-674d267133ec)

**Comment by LupertEverett** [comment]
> File/Edit/etc bar I would expect a click to do something

From what I've seen over checking the source code, it is not a real toolbar, it is just a single line of text.

**Comment by dpjudas** [comment]
Yes, the editor is basically just a mock up currently.
