### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [dpjudas/SurrealEngine#6]
I will be nice to have [demo](https://archive.org/details/UnrealTournament) support to be able to test this without buying the full game.

**Comment by dpjudas** [comment]
This is pretty low on my priority list. Right now I just want to successfully play a game of instagib with the bots. :)

If someone were to add the support I'd gladly merge the PR. Overall I don't think it would require too much as it is essentially just the normal UT with fewer packages.

**Comment by neuromancer** [comment]
A quick try with the demo:

```
$ wget "https://archive.org/download/UnrealTournament/UTDemo338.exe"
$ unzip "UTDemo338.exe"
```

(after compiling UTEngine and changing the path)

```
$ ./UTEngine 
Unhandled exception: Could not find class object for SimpleCommandlet
```

If we had support, we could fetch it in the CI test to make sure it parses the files.

**Comment by dpjudas** [comment]
Oh, that sounds like the demo is a bit closer to Unreal Gold than 432/436 then. There I had to declare a native SimpleCommandlet class as well.

In Package.cpp line 53 there's a check for Unreal 1. You could try force that always to true to see if that is enough to get it to load it.

Given how low that 338 number is I fear that it will require a bit more than just this to get it going. On the plus side, any code added to support the demo release will also help on getting some Unreal 1 support.

**Comment by dpjudas** [comment]
I gave it a run myself and I got it to load some of the maps with only a few changes. However, there's clearly some changes in the input system as the mouse starts to drift in the 338 version.

For the time being I think it is best if this is considered highly experimental support. In the future it could probably be fully supported. :)

**Comment by neuromancer** [comment]
Great, I tested and it returns "Unhandled exception: Unable to find Vulkan", but that's probably another issue.

**Comment by dpjudas** [comment]
Yes, that error means it cannot find any support for vulkan on your system. It shouldn't be related to the demo support.

**Comment by leilei-** [comment]
FYI there's also a later 348 demo and an earlier 322 demo (aka the "3dfx demo").

**Comment by dpjudas** [comment]
Do you know the links to the those versions? Having a copy of each version of UT out there would be handy for testing. Supporting them would be mostly for completeness sake as I think people that want to play the game should buy it.

**Comment by leilei-** [comment]
The later demo's easy to find

http://www.fpsnetwork.com/downloads/ut99/new/Demo/utdemo348.exe

http://www.ut-files.com/index.php?dir=UT_Demo/Demo/&file=utdemo348.exe

the earlier demo is more difficult to directly link to (one server that has one also has warez in the same folder), so instead i'll just link to an old polish corporate site that happens to still have a working download in 2021

https://www.pcworld.pl/ftp/gry_320/Unreal-Tournament-Demo.html

**Comment by dpjudas** [comment]
Thanks, leilei. That polish site worked out nicely.

On a related note, I found this list of games using UE1 in the version ranges used by Unreal 1 and UT: 

https://wiki.beyondunreal.com/Legacy:Unreal_Engine_Versions/1#Released_Projects

All those games in the 300-436 range would probably be relatively easy to support - assuming they didn't make extensive changes to the engine itself. If Unreal 1 support is also improved the 200-300 version games should also be doable.

**Comment by leilei-** [comment]
I can see Wheel of Time and Nerf Arena Blast happening (they also have demos). Rune uses a new skeletal model format of its own so that's unlikely.   DS9 The Fallen probably also has its own seeletal implementation.

Klingon Honor Guard's got a demo but the vertex mesh format's a little different IIRC?

**Comment by dpjudas** [comment]
I think I managed to track down most of the package version 61 compatibility issues. At least now Unreal will actually play its intro map (and its menus) with all the unreal script running the show.

Klingon Honor Guard unfortunately still won't boot. It seems the font format has changed. I'm not entirely sure if this is a KHG modification or if older Unreal versions uses a different format. The only Unreal 1 version I got is the gold version (226).

In any case, the fact that Unreal Gold now runs means the engine differences between all those games aren't really that big. :)

**Comment by rea987** [comment]
Actually, some people in Rune community has access to Rune source code but as Human Head Studios is no more, I guess, that's legally a dead end.

**Comment by neuromancer** [comment]
Can someone try with the [Clive Barker's Undying Demo](https://archive.org/details/undying_demo) ?

**Comment by leilei-** [comment]
Undying uses Miles and a skeletal model format of its own doesn't it

One problem of that unreal wiki list is that it's only listing what it's derived from, not necessarily for feature parity.   Probably the only newer (2001+) UE1 game that has a chance of working is Adventure Pinball, and maybe XCOM Enforcer.

Also proposing legally unclear source code use is toxic to a clean room project.
