### ISSUE TITLE
Fails to build near the end

### ISSUE THREAD

**Issue by coreybruce** [dpjudas/SurrealEngine#82]
Hey just wanted to report that right need the end of the compiling it fails, I am using Manjaro x64

```
[ 99%] Building CXX object CMakeFiles/SurrealDebugger.dir/SurrealEngine/MainDebugger.cpp.o
[ 99%] Building CXX object CMakeFiles/SurrealEditor.dir/SurrealEngine/MainEditor.cpp.o
[ 99%] Building CXX object CMakeFiles/SurrealEngine.dir/SurrealEngine/MainGame.cpp.o
[ 99%] Linking CXX executable SurrealEngine
[ 99%] Linking CXX executable SurrealEditor
/usr/bin/ld: cannot open output file SurrealEngine: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/SurrealEngine.dir/build.make:102: SurrealEngine] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: CMakeFiles/SurrealEngine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable SurrealDebugger
[100%] Built target SurrealEditor
[100%] Built target SurrealDebugger
make: *** [Makefile:136: all] Error 2
```

**Comment by LupertEverett** [comment]
I _think_ you're trying to build it from the project's root directory, thus `ld` gets confused because `SurrealEngine` is also a folder within the project's root folder.

Try to make a "build" folder and compile everything from there:

`mkdir build`
`cd build`
`cmake ..`
`make`

**Comment by coreybruce** [comment]
> I _think_ you're trying to build it from the project's root directory, thus `ld` gets confused because `SurrealEngine` is also a folder within the project's root folder.
> 
> Try to make a "build" folder and compile everything from there:
> 
> `mkdir build` `cd build` `cmake ..` `make`

Thanks those instructions worked, the developer should have proper instructions on the readme on how to build instead of just saying "Use CMake to build the project."

**Comment by dpjudas** [comment]
Sorry, I never made such a instruction since I didn't know this was a problem in the first place. There are so many ways things can be set up that it is difficult to know about every situation, especially on Linux.

That's why the instruction is so generic - packages have different names depending on distro. They have different compilers (gcc vs clang), different versions of the compiler, etc.

That said, we could rename the sources folder to avoid this situation, or maybe rename the executable on Linux. The exe should probably be renamed to surreal-engine. Using CamelCase for executables on Linux makes things look out of place.

**Comment by LupertEverett** [comment]
I think we can put the instructions I've given here into the README as well

**Comment by coreybruce** [comment]
Awesome thanks also I would suggest doing ```make -j(nproc)``` instead of ```make -j 16``` on the build instructions so it will automatically use the cores a system has instead of assuming there is 16 for example. :smiley:

**Comment by coreybruce** [comment]
> Sorry, I never made such a instruction since I didn't know this was a problem in the first place. There are so many ways things can be set up that it is difficult to know about every situation, especially on Linux.
> 
> That's why the instruction is so generic - packages have different names depending on distro. They have different compilers (gcc vs clang), different versions of the compiler, etc.
> 
> That said, we could rename the sources folder to avoid this situation, or maybe rename the executable on Linux. The exe should probably be renamed to surreal-engine. Using CamelCase for executables on Linux makes things look out of place.

Hey it's all good and not that complicated at all on Linux while also being pretty universal, all Linux distros will contain gcc, make, cmake etc so if you are using make and cmake then all distros will support it and have the same compilers. :+1:
