### ISSUE TITLE
I can't run Rune game

### ISSUE THREAD

**Issue by DJs3000** [dpjudas/SurrealEngine#87]
Hello. I use linux(Debian like). SurrealEngine compiles without problems. I can't figure out how to run the game. I bought "Rune Classic" on Steam and put the SurrealEngine and SurrealEngine.pk3 files in "System" folder. If I try to launch a game, I always get the answer "Unable to find a game folder". What am I doing wrong?

**Comment by chekoopa** [comment]
Just walking by, but make sure that the game version is v1.10. `Rune.exe` should have SHA1 hash `4a517c7f96a27cf7e25534c80d50af8db4065276`.

**Comment by LupertEverett** [comment]
Maybe Steam version of Rune is adding something to the executable, resulting in a different SHA1 sum. Apparently that was the case with Steam versions of Unreal, UT and Deus Ex.

That being said, Rune support is practically non existent atm, SurrealEngine crashes almost immediately when you try to run it.

**Comment by DJs3000** [comment]
Which game is currently running? UT99?

**Comment by LupertEverett** [comment]
> Which game is currently running? UT99?

UT99 v436 and Unreal Gold v226. Deus Ex boots to intro, but doesn't accept any sorts of input atm

**Comment by LupertEverett** [comment]
Sadly you cannot, as Epic has taken down all of the Unreal/Tournament games in various stores.

**Comment by perondeidad** [comment]
> Where can I buy UT99 v436?

just search "freegoggames"
