### ISSUE TITLE
it's not possible to retrieve Flak Cannon on DM-Agony (collision checking issue?)

### ISSUE THREAD

**Issue by Mis012** [dpjudas/SurrealEngine#92]
it's not possible to retrieve Flak Cannon on DM-Agony, crouching doesn't seem to result in a shorter collision box? If it does, it's still not short enough for whatever reason

**Comment by OrdinaryMagician** [comment]
This is not a bug, it's entirely vanilla behavior for the collision height to remain the same when crouching.

**Comment by Mis012** [comment]
hm, is there some trickery in DM-Agony then? to simulate the same effect

**Comment by Mis012** [comment]
hm, I tried now and it seems so indeed, no need to crouch

**Comment by Mis012** [comment]
that's... curious

**Comment by Mis012** [comment]
that would imply the issue is more with the floor than the ceiling?

**Comment by Xaleros** [comment]
im able to reproduce this, i'll see if i can pin that down sometime soon

**Comment by Xaleros** [comment]
so, in `UActor::TickWalking()`, it seems like the"step up" part of movement handled by `TryMove(stepUpDelta)` is causing the player to bump into the ceiling, working on a fix

**Comment by Xaleros** [comment]
Fix should be up, give it a shot and let me know if that fixes it for you as well

**Comment by Mis012** [comment]
yup, seems fixed
I noticed some other funky stuff possibly related to step up handling, walking onto the shock rifle "platform" sometimes results in a "warp" kind of feeling, rather than continuous motion; and moving towards a platform's edge while falling feels weird
